//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIScriptWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UIScript), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("OnEnable", OnEnable);
		L.RegFunction("OnDisable", OnDisable);
		L.RegFunction("Btn_OnClick", Btn_OnClick);
		L.RegFunction("Btn_OnMouseOver", Btn_OnMouseOver);
		L.RegFunction("Btn_OnMouseOut", Btn_OnMouseOut);
		L.RegFunction("Btn_OnPress", Btn_OnPress);
		L.RegFunction("Btn_OnPressure", Btn_OnPressure);
		L.RegFunction("Btn_OnRelease", Btn_OnRelease);
		L.RegFunction("Btn_OnDoubleClick", Btn_OnDoubleClick);
		L.RegFunction("OnTweenFinished", OnTweenFinished);
		L.RegFunction("OnTypeWriterFinished", OnTypeWriterFinished);
		L.RegFunction("OnInputChange", OnInputChange);
		L.RegFunction("OnInputSubmit", OnInputSubmit);
		L.RegFunction("OnSelect", OnSelect);
		L.RegFunction("OnDeselect", OnDeselect);
		L.RegFunction("OnUIInputValueChange", OnUIInputValueChange);
		L.RegFunction("OnUIInputSubmit", OnUIInputSubmit);
		L.RegFunction("OnUIProgressBarValueChange", OnUIProgressBarValueChange);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ScriptName", get_ScriptName, set_ScriptName);
		L.RegVar("IsTrigger", get_IsTrigger, set_IsTrigger);
		L.RegVar("List_Sprite", get_List_Sprite, set_List_Sprite);
		L.RegVar("List_Label", get_List_Label, set_List_Label);
		L.RegVar("List_Button", get_List_Button, set_List_Button);
		L.RegVar("List_Slider", get_List_Slider, set_List_Slider);
		L.RegVar("List_Grid", get_List_Grid, set_List_Grid);
		L.RegVar("List_Toggle", get_List_Toggle, set_List_Toggle);
		L.RegVar("List_Element", get_List_Element, set_List_Element);
		L.RegVar("List_Object", get_List_Object, set_List_Object);
		L.RegVar("List_ShaderObject", get_List_ShaderObject, set_List_ShaderObject);
		L.RegVar("List_Texture", get_List_Texture, set_List_Texture);
		L.RegVar("List_Table", get_List_Table, set_List_Table);
		L.RegVar("List_ProgressBar", get_List_ProgressBar, set_List_ProgressBar);
		L.RegVar("List_animation", get_List_animation, set_List_animation);
		L.RegVar("List_PopupList", get_List_PopupList, set_List_PopupList);
		L.RegVar("List_Input", get_List_Input, set_List_Input);
		L.RegVar("List_ScrollView", get_List_ScrollView, set_List_ScrollView);
		L.RegVar("List_ScrollBar", get_List_ScrollBar, set_List_ScrollBar);
		L.RegVar("List_SpriteAnimation", get_List_SpriteAnimation, set_List_SpriteAnimation);
		L.RegVar("List_TweenPosition", get_List_TweenPosition, set_List_TweenPosition);
		L.RegVar("List_TweenScale", get_List_TweenScale, set_List_TweenScale);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEnable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			obj.OnEnable();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDisable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			obj.OnDisable();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Btn_OnClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Btn_OnClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Btn_OnMouseOver(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Btn_OnMouseOver(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Btn_OnMouseOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Btn_OnMouseOut(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Btn_OnPress(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Btn_OnPress(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Btn_OnPressure(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Btn_OnPressure(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Btn_OnRelease(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Btn_OnRelease(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Btn_OnDoubleClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Btn_OnDoubleClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnTweenFinished(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.OnTweenFinished(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnTypeWriterFinished(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.OnTypeWriterFinished(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInputChange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.OnInputChange(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInputSubmit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.OnInputSubmit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnSelect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 2);
			obj.OnSelect(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDeselect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 2);
			obj.OnDeselect(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUIInputValueChange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UIInput arg0 = (UIInput)ToLua.CheckObject(L, 2, typeof(UIInput));
			obj.OnUIInputValueChange(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUIInputSubmit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UIInput arg0 = (UIInput)ToLua.CheckObject(L, 2, typeof(UIInput));
			obj.OnUIInputSubmit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUIProgressBarValueChange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIScript obj = (UIScript)ToLua.CheckObject<UIScript>(L, 1);
			UIProgressBar arg0 = (UIProgressBar)ToLua.CheckObject<UIProgressBar>(L, 2);
			obj.OnUIProgressBarValueChange(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScriptName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			string ret = obj.ScriptName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ScriptName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsTrigger(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			bool ret = obj.IsTrigger;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsTrigger on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Sprite(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISprite> ret = obj.List_Sprite;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Sprite on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Label(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UILabel> ret = obj.List_Label;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Label on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Button(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIButton> ret = obj.List_Button;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Button on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Slider(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISlider> ret = obj.List_Slider;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Slider on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Grid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIGrid> ret = obj.List_Grid;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Grid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Toggle(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIToggle> ret = obj.List_Toggle;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Toggle on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Element(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIElement> ret = obj.List_Element;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Element on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Object(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UnityEngine.GameObject> ret = obj.List_Object;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Object on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_ShaderObject(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UnityEngine.Shader> ret = obj.List_ShaderObject;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ShaderObject on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Texture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UITexture> ret = obj.List_Texture;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Texture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Table(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UITable> ret = obj.List_Table;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Table on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_ProgressBar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIProgressBar> ret = obj.List_ProgressBar;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ProgressBar on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_animation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISpriteAnimation> ret = obj.List_animation;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_animation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_PopupList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIPopupList> ret = obj.List_PopupList;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_PopupList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_Input(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIInput> ret = obj.List_Input;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Input on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_ScrollView(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIScrollView> ret = obj.List_ScrollView;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ScrollView on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_ScrollBar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIScrollBar> ret = obj.List_ScrollBar;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ScrollBar on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_SpriteAnimation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISpriteAnimation> ret = obj.List_SpriteAnimation;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_SpriteAnimation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_TweenPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<TweenPosition> ret = obj.List_TweenPosition;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_TweenPosition on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List_TweenScale(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<TweenScale> ret = obj.List_TweenScale;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_TweenScale on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ScriptName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.ScriptName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ScriptName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_IsTrigger(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.IsTrigger = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsTrigger on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Sprite(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISprite> arg0 = (System.Collections.Generic.List<UISprite>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UISprite>));
			obj.List_Sprite = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Sprite on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Label(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UILabel> arg0 = (System.Collections.Generic.List<UILabel>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UILabel>));
			obj.List_Label = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Label on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Button(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIButton> arg0 = (System.Collections.Generic.List<UIButton>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIButton>));
			obj.List_Button = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Button on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Slider(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISlider> arg0 = (System.Collections.Generic.List<UISlider>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UISlider>));
			obj.List_Slider = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Slider on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Grid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIGrid> arg0 = (System.Collections.Generic.List<UIGrid>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIGrid>));
			obj.List_Grid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Grid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Toggle(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIToggle> arg0 = (System.Collections.Generic.List<UIToggle>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIToggle>));
			obj.List_Toggle = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Toggle on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Element(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIElement> arg0 = (System.Collections.Generic.List<UIElement>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIElement>));
			obj.List_Element = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Element on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Object(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UnityEngine.GameObject> arg0 = (System.Collections.Generic.List<UnityEngine.GameObject>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.GameObject>));
			obj.List_Object = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Object on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_ShaderObject(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UnityEngine.Shader> arg0 = (System.Collections.Generic.List<UnityEngine.Shader>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Shader>));
			obj.List_ShaderObject = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ShaderObject on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Texture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UITexture> arg0 = (System.Collections.Generic.List<UITexture>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UITexture>));
			obj.List_Texture = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Texture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Table(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UITable> arg0 = (System.Collections.Generic.List<UITable>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UITable>));
			obj.List_Table = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Table on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_ProgressBar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIProgressBar> arg0 = (System.Collections.Generic.List<UIProgressBar>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIProgressBar>));
			obj.List_ProgressBar = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ProgressBar on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_animation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISpriteAnimation> arg0 = (System.Collections.Generic.List<UISpriteAnimation>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UISpriteAnimation>));
			obj.List_animation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_animation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_PopupList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIPopupList> arg0 = (System.Collections.Generic.List<UIPopupList>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIPopupList>));
			obj.List_PopupList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_PopupList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_Input(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIInput> arg0 = (System.Collections.Generic.List<UIInput>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIInput>));
			obj.List_Input = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_Input on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_ScrollView(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIScrollView> arg0 = (System.Collections.Generic.List<UIScrollView>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIScrollView>));
			obj.List_ScrollView = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ScrollView on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_ScrollBar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UIScrollBar> arg0 = (System.Collections.Generic.List<UIScrollBar>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UIScrollBar>));
			obj.List_ScrollBar = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_ScrollBar on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_SpriteAnimation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<UISpriteAnimation> arg0 = (System.Collections.Generic.List<UISpriteAnimation>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UISpriteAnimation>));
			obj.List_SpriteAnimation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_SpriteAnimation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_TweenPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<TweenPosition> arg0 = (System.Collections.Generic.List<TweenPosition>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<TweenPosition>));
			obj.List_TweenPosition = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_TweenPosition on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_List_TweenScale(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIScript obj = (UIScript)o;
			System.Collections.Generic.List<TweenScale> arg0 = (System.Collections.Generic.List<TweenScale>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<TweenScale>));
			obj.List_TweenScale = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index List_TweenScale on a nil value");
		}
	}
}

